# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldlink', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='model_pic',
            field=models.ImageField(default='static/images/profile-default.png', upload_to='profile-images/'),
        ),
    ]
