# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldlink', '0003_remove_profile_model_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='static/images/profile-default.png', upload_to='profile-images/'),
        ),
    ]
