# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldlink', '0004_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='static/images/profile-default.png', upload_to='worldlink/static/images'),
        ),
    ]
