# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldlink', '0005_auto_20170823_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_url',
            field=models.CharField(default='photos/profile-default.png', max_length=50),
        ),
    ]
