# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldlink', '0007_auto_20170823_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='worldlink/static/images', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.CharField(default='', max_length=50),
        ),
    ]
