# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldlink', '0008_auto_20170829_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='worldlink/static/images', verbose_name='Image'),
        ),
    ]
